Repository BC-MAY-21-RN/proyecto-final-pf-f22-t1, pull requests merged in 2022-05, with the labels that each got.

#10 Feature#9 notes page layout
  bethink/src/components/home/ContainerMain.js
  bethink/src/components/home/DarkSwitch.js
  bethink/src/components/home/DisplayUser.js
  bethink/src/components/home/LightSwitch.js
  bethink/src/components/home/LoveNotes.js
  bethink/src/components/home/Reminders.js
  bethink/src/components/home/SectionName.js
  bethink/src/components/navigation/IconsTab.js
  bethink/src/components/notes/ButtonAddNotes.js
  bethink/src/components/notes/CardNotes.js
  bethink/src/components/notes/PriorityNotes.js
  bethink/src/hooks/useAnimation.js
  bethink/src/imgs/notes/emoji1.png
  bethink/src/imgs/notes/emoji2.png
  bethink/src/imgs/notes/emoji3.png
  bethink/src/imgs/notes/nonotes.png
  bethink/src/imgs/notes/notes.png
  bethink/src/navigation/appNavigation/AppNavigation.js
  bethink/src/navigation/appNavigation/TabNavigation.js
  bethink/src/reducers/uiSlice.js
  bethink/src/screens/home/HomeScreen.js
  bethink/src/screens/notes/NotesScreen.js
Labels: mentor review required, ready to merge, review required

#19 Feature#13 new note firebase
  bethink/.eslintrc.js
  bethink/package-lock.json
  bethink/package.json
  bethink/src/actions/notes.js
  bethink/src/components/drawerNav/CustomDrawer.js
  bethink/src/components/home/ConditionNotes.js
  bethink/src/components/home/Date.js
  bethink/src/components/home/LoadingNotes.js
  bethink/src/components/home/Logo.js
  bethink/src/components/home/LoveNotes.js
  bethink/src/components/home/NoLoves.js
  bethink/src/components/home/SectionMain.js
  bethink/src/components/notes/AddNote.js
  bethink/src/components/notes/BtnAddNote.js
  bethink/src/components/notes/ButtonAddNotes.js
  bethink/src/components/notes/CardNotes.js
  bethink/src/components/notes/ModalCompleteForm.js
  bethink/src/components/notes/NoNotes.js
  bethink/src/components/notes/PriorityNote.js
  bethink/src/helpers/getDate.js
  bethink/src/hooks/useAnimationLike.js
  bethink/src/hooks/useAnimationSkeleto.js
  bethink/src/imgs/home/noloves.png
  bethink/src/navigation/appNavigation/AppNavigation.js
  bethink/src/navigation/appNavigation/TabNavigation.js
  bethink/src/reducers/notesSlice.js
  bethink/src/screens/home/HomeScreen.js
  bethink/src/screens/notes/NewNoteScreen.js
  bethink/src/screens/notes/NotesScreen.js
  bethink/src/store/store.js
  bethink/yarn.lock
Labels: mentor review required, ready to merge, review required

#20 Feature#14 security note
  bethink/android/app/build.gradle
  bethink/android/app/src/main/AndroidManifest.xml
  bethink/android/app/src/main/java/com/bethink/MainApplication.java
  bethink/android/build.gradle
  bethink/android/settings.gradle
  bethink/package-lock.json
  bethink/package.json
  bethink/src/actions/notes.js
  bethink/src/components/home/ContainerHome.js
  bethink/src/components/home/LoveNotes.js
  bethink/src/components/navigation/IconsDrawer.js
  bethink/src/components/notes/AddNoteName.js
  bethink/src/components/notes/BtnAddNote.js
  bethink/src/components/notes/BtnEditNote.js
  bethink/src/components/notes/BtnSave.js
  bethink/src/components/notes/CardListNote.js
  bethink/src/components/notes/CardNotes.js
  bethink/src/components/notes/ConditionalNotes.js
  bethink/src/components/notes/ContainerEditNote.js
  bethink/src/components/notes/ModalPinNote.js
  bethink/src/components/notes/TitleNote.js
  bethink/src/components/notes/TitleNoteCard.js
  bethink/src/components/pin/ActionPin.js
  bethink/src/components/pin/BtnDelete.js
  bethink/src/components/pin/BtnEntry.js
  bethink/src/components/pin/ModalMain.js
  bethink/src/components/pin/ModalPinContainer.js
  bethink/src/components/pin/ModalRow.js
  bethink/src/components/pin/NumbersPin.js
  bethink/src/components/pin/btnStyles.js
  bethink/src/components/settings/ContainerItemSecurity.js
  bethink/src/components/settings/ContainerPin.js
  bethink/src/components/settings/ItemSecurity.js
  bethink/src/components/settings/ModalBtn.js
  bethink/src/components/settings/ModalClose.js
  bethink/src/components/settings/ModalInput.js
  bethink/src/components/settings/ModalPin.js
  bethink/src/components/settings/SecureSettings.js
  bethink/src/components/settings/SwitchSettings.js
  bethink/src/helpers/storageSecurity.js
  bethink/src/imgs/settings/password.png
  bethink/src/navigation/appNavigation/AppNavigation.js
  bethink/src/navigation/appNavigation/TabNavigation.js
  bethink/src/reducers/notesSlice.js
  bethink/src/reducers/uiSlice.js
  bethink/src/screens/home/HomeScreen.js
  bethink/src/screens/notes/EditNoteScreen.js
  bethink/src/screens/notes/NewNoteScreen.js
  bethink/src/screens/notes/NotesScreen.js
  bethink/src/screens/settings/SettingsScreen.js
  bethink/yarn.lock
Labels: review required

#21 Feature#16 love notes screen
  bethink/src/components/home/ConditionNotes.js
  bethink/src/components/home/ContainerHome.js
  bethink/src/components/home/LoveNotes.js
  bethink/src/components/loveNotes/ConditionalLoveNotes.js
  bethink/src/components/notes/AddNoteName.js
  bethink/src/components/notes/CardNotes.js
  bethink/src/components/notes/ConditionalNotes.js
  bethink/src/components/notes/ModalPinNote.js
  bethink/src/components/pin/ActionPin.js
  bethink/src/components/pin/BtnEntry.js
  bethink/src/components/pin/ModalMain.js
  bethink/src/components/pin/ModalPinContainer.js
  bethink/src/components/settings/ModalClose.js
  bethink/src/helpers/fingerPrint.js
  bethink/src/imgs/notes/nolovesnotes.png
  bethink/src/reducers/uiSlice.js
  bethink/src/screens/home/HomeScreen.js
  bethink/src/screens/notes/LoveNotesScreen.js
  bethink/src/screens/notes/NotesScreen.js
Labels: review required

#24 Delete notes,
  bethink/src/components/notes/ConditionalNotes.js
  bethink/src/components/notes/ContainerEditNote.js
  bethink/src/components/notes/DeleteBtn.js
  bethink/src/components/notes/DeleteMain.js
  bethink/src/components/notes/DeleteNote.js
  bethink/src/components/notes/ModalDelete.js
  bethink/src/helpers/fingerPrint.js
  bethink/src/imgs/notes/deletenote.png
  bethink/src/navigation/appNavigation/TabNavigation.js
  bethink/src/screens/notes/NotesScreen.js
Labels: mentor review required, ready to merge, review required

#28 form reminders
  bethink/package-lock.json
  bethink/package.json
  bethink/src/components/reminders/BtnAddReminder.js
  bethink/src/components/reminders/ButtonAddReminders.js
  bethink/src/components/reminders/DateReminder.js
  bethink/src/components/reminders/ModalCompleteReminders.js
  bethink/src/components/reminders/TitleReminder.js
  bethink/src/helpers/getDate.js
  bethink/src/navigation/appNavigation/TabNavigation.js
  bethink/src/screens/reminders/NewReminderScreen.js
  bethink/src/screens/reminders/ReminderScreensDone.js
  bethink/src/screens/reminders/RemindersScreenToDo.js
  bethink/yarn.lock
Labels: mentor review required, ready to merge, review required

#30 edit reminder,
  bethink/src/components/reminders/BtnEditReminder.js
  bethink/src/components/reminders/CardReminders.js
  bethink/src/components/reminders/Done/CardsDone.js
  bethink/src/components/reminders/ModalEdit.js
  bethink/src/components/reminders/StatusReminder.js
  bethink/src/reducers/remindersSlice.js
  bethink/src/screens/reminders/ReminderScreensDone.js
  bethink/src/screens/reminders/RemindersScreenToDo.js
Labels: mentor review required, review required

#32 reminders in home page
  README.md
  bethink/android/app/build.gradle
  bethink/android/app/src/main/java/com/bethink/MainActivity.java
  bethink/android/app/src/main/java/com/bethink/MainApplication.java
  bethink/android/app/src/main/res/drawable/logo.png
  bethink/android/app/src/main/res/layout/launch_screen.xml
  bethink/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  bethink/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  bethink/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  bethink/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  bethink/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  bethink/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  bethink/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  bethink/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  bethink/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  bethink/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  bethink/android/app/src/main/res/values/colors.xml
  bethink/android/settings.gradle
  bethink/package-lock.json
  bethink/package.json
  bethink/src/components/home/DisplayUser.js
  bethink/src/components/home/LoadingReminders.js
  bethink/src/components/home/NoMore.js
  bethink/src/components/home/NoReminders.js
  bethink/src/components/home/Reminders.js
  bethink/src/imgs/home/nomore.png
  bethink/src/imgs/home/notimes.png
  bethink/src/navigation/Navigation.js
  bethink/yarn.lock
  design/Add note dark-1.png
  design/Add note dark.png
  design/Home dark.png
  design/Home light.png
  design/Login validaciones.png
  design/Login.png
  design/New Reminders Dark.png
  design/No notes dark.png
  design/No notes light.png
  design/Notes dark.png
  design/Notes light.png
  design/Reminders Dark-1.png
  design/Reminders Dark-2.png
  design/Reminders Dark.png
  design/Reminders Light.png
  design/Signup.png
Labels: mentor review required, ready to merge, review required
